/**
 * Guest Service Requests API
 * GET /api/guest/service-requests - Fetch all service requests for the guest
 * POST /api/guest/service-requests - Create a new service request
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireGuest } from '@/lib/auth/middleware';
import { isSalesforceEnabled } from '@/lib/workato/feature-flags';
import { getSalesforceClient } from '@/lib/workato/config';
import { executeQuery, executeQueryOne, executeUpdate, generateId, formatDate } from '@/lib/db/client';
import { mapServiceRequest } from '@/lib/db/mappers';
import { ServiceRequestRow, UserRow, ServiceRequestType, Priority } from '@/types';
import { ValidationError, NotFoundError, ExternalServiceError } from '@/lib/errors';
import { createErrorResponse } from '@/lib/errors/api-response';
import { generateIdempotencyToken } from '@/lib/utils/idempotency';

/**
 * GET /api/guest/service-requests
 * Fetch all service requests for the authenticated guest
 * Optionally enriches with Salesforce Case data if Case ID exists
 */
export async function GET(request: NextRequest) {
  try {
    const session = await requireGuest(request);
    
    if (isSalesforceEnabled()) {
      // Use Salesforce via Workato
      const client = getSalesforceClient();
      const requests = await client.searchServiceRequests({ guest_id: session.userId });
      
      return NextResponse.json({ requests });
    } else {
      // Use local database only (no Salesforce enrichment)
      const requestsQuery = `
        SELECT * FROM service_requests
        WHERE guest_id = ?
        ORDER BY created_at DESC
      `;
      const requestRows = executeQuery<ServiceRequestRow>(requestsQuery, [session.userId]);
      const requests = requestRows.map(mapServiceRequest);

      return NextResponse.json({ requests });
    }
    
  } catch (error) {
    return createErrorResponse(error, 'GET /api/guest/service-requests');
  }
}

/**
 * POST /api/guest/service-requests
 * Create a new service request with Salesforce Case integration
 */
export async function POST(request: NextRequest) {
  try {
    const session = await requireGuest(request);
    const body = await request.json();
    
    // Validate input
    const { type, priority, description } = body;
    
    if (!type || !priority || !description) {
      throw new ValidationError('Type, priority, and description are required');
    }
    
    // Validate type
    const validTypes: ServiceRequestType[] = ['housekeeping', 'room_service', 'maintenance', 'concierge'];
    if (!validTypes.includes(type)) {
      throw new ValidationError('Invalid service request type');
    }
    
    // Validate priority
    const validPriorities: Priority[] = ['low', 'medium', 'high'];
    if (!validPriorities.includes(priority)) {
      throw new ValidationError('Invalid priority');
    }
    
    // Get guest details
    const guestQuery = `SELECT * FROM users WHERE id = ?`;
    const guest = executeQueryOne<UserRow>(guestQuery, [session.userId]);
    
    if (!guest || !guest.room_number) {
      throw new NotFoundError('Guest or room');
    }
    
    if (isSalesforceEnabled()) {
      // Use Salesforce via Workato
      const client = getSalesforceClient();
      
      // Split guest name into first and last name
      const nameParts = guest.name.split(' ');
      const firstName = nameParts[0] || '';
      const lastName = nameParts.slice(1).join(' ') || nameParts[0] || '';
      
      const serviceRequest = await client.createServiceRequest({
        // Token will be auto-generated by Salesforce client
        guest_email: guest.email,
        guest_first_name: firstName,
        guest_last_name: lastName,
        room_number: guest.room_number,
        type,
        priority,
        description,
      });
      
      return NextResponse.json({
        success: true,
        request: serviceRequest,
      }, { status: 201 });
    } else {
      // Use local database only (no Salesforce Case integration)
      // Note: When SALESFORCE_ENABLED=true, Salesforce Case creation
      // is handled by SalesforceClient.createServiceRequest()

      const requestId = generateId();
      const idempotencyToken = generateIdempotencyToken();
      const now = formatDate(new Date());

      // Create service request in local database only
      executeUpdate(
        `INSERT INTO service_requests (
          id, guest_id, room_number, type, priority, description, status, salesforce_ticket_id, idempotency_token, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [requestId, session.userId, guest.room_number, type, priority, description, 'pending', null, idempotencyToken, now]
      );

      // Fetch the created request
      const createdRequest = executeQueryOne<ServiceRequestRow>(
        `SELECT * FROM service_requests WHERE id = ?`,
        [requestId]
      );

      if (!createdRequest) {
        throw new ValidationError('Failed to create service request');
      }

      return NextResponse.json({
        success: true,
        request: mapServiceRequest(createdRequest),
        idempotency_token: idempotencyToken,
      }, { status: 201 });
    }
    
  } catch (error) {
    return createErrorResponse(error, 'POST /api/guest/service-requests');
  }
}
